### ISSUE TITLE
Adapting the code to read 1 million words using dynamic string array

### ISSUE THREAD

**Issue by itzomen** [itzomen/C-mini-projects#1]
### Create a dynamic array
RUN words_occurrences_v3errors.c to see errors
I want to create a dynamic array so that it will be able to read approximately one million words but I'm having issues doing that.

The limited number of words it can read now is approximately 40000 using stack allocation. I have tried using malloc and realloc to create a dynamic array using the snippet bellow but i ran into issues with the string functions i.e exeption error or segmentation fault
msvcrt.dll!strcpy 
or after some modification, I get msvcrt.dll!msvcrt?_strcpy

**Snippet I used**
`size_t MAX_WORDS = 1000; char words = (char)malloc(MAX_WORDS * sizeof(words)); if (words == NULL){ printf("mem not allocated\n"); printf("Verify the path and try again\n"); getchar(); exit(EXIT_FAILURE); } if (MAX_WORDS == index+1) { MAX_WORDS = 2; words = (char)realloc(words, MAX_WORDS * sizeof(*words)); if (words == NULL){ printf("mem no aloc\n"); printf("Verify the path and try again\n"); getchar(); exit(EXIT_FAILURE); } }`

**Comment by xasterKies** [comment]
OK dude am on it!

**Comment by itzomen** [comment]
dynamic array created fixed
check version 3

**Comment by Daniel-TheProgrammer** [comment]
Great one boss..
